use super::{does_catch_events, mouse::MouseState};
use bevy_ecs::prelude::*;
use bevy_input::{
    ButtonState,
    keyboard::{Key as BevyKey, KeyCode as BevyKeyCode, KeyboardInput},
    prelude::*,
};
use blitz_dom::*;
use blitz_traits::events::{BlitzKeyEvent, KeyState, UiEvent};
use dioxus::prelude::*;
use dioxus_native::*;

pub(crate) fn handle_keyboard_events(
    mut dioxus_doc: NonSendMut<DioxusDocument>,
    mut keyboard_input_events: ResMut<Events<KeyboardInput>>,
    mut keys: ResMut<ButtonInput<BevyKeyCode>>,
    mut last_mouse_state: Local<MouseState>,
) {
    if keyboard_input_events.is_empty() {
        return;
    }

    for event in keyboard_input_events
        .get_cursor()
        .read(&keyboard_input_events)
    {
        let modifier = match event.logical_key {
            BevyKey::Alt => Some(Modifiers::ALT),
            BevyKey::AltGraph => Some(Modifiers::ALT_GRAPH),
            BevyKey::CapsLock => Some(Modifiers::CAPS_LOCK),
            BevyKey::Control => Some(Modifiers::CONTROL),
            BevyKey::Fn => Some(Modifiers::FN),
            BevyKey::FnLock => Some(Modifiers::FN_LOCK),
            BevyKey::NumLock => Some(Modifiers::NUM_LOCK),
            BevyKey::ScrollLock => Some(Modifiers::SCROLL_LOCK),
            BevyKey::Shift => Some(Modifiers::SHIFT),
            BevyKey::Symbol => Some(Modifiers::SYMBOL),
            BevyKey::SymbolLock => Some(Modifiers::SYMBOL_LOCK),
            BevyKey::Meta => Some(Modifiers::META),
            BevyKey::Hyper => Some(Modifiers::HYPER),
            BevyKey::Super => Some(Modifiers::SUPER),
            _ => None,
        };
        if let Some(modifier) = modifier {
            match event.state {
                ButtonState::Pressed => last_mouse_state.mods.insert(modifier),
                ButtonState::Released => last_mouse_state.mods.remove(modifier),
            };
        }
        let key_state = match event.state {
            ButtonState::Pressed => KeyState::Pressed,
            ButtonState::Released => KeyState::Released,
        };
        let blitz_key_event = BlitzKeyEvent {
            key: bevy_key_to_blitz_key(&event.logical_key),
            code: bevy_key_code_to_blitz_code(&event.key_code),
            modifiers: last_mouse_state.mods,
            location: Location::Standard,
            is_auto_repeating: event.repeat,
            is_composing: false,
            state: key_state,
            text: event.text.clone(),
        };

        match key_state {
            KeyState::Pressed => {
                dioxus_doc.handle_ui_event(UiEvent::KeyDown(blitz_key_event));
            }
            KeyState::Released => {
                dioxus_doc.handle_ui_event(UiEvent::KeyUp(blitz_key_event));
            }
        }
    }

    let should_catch_events = dioxus_doc
        .hit(last_mouse_state.x, last_mouse_state.y)
        .map(|hit| does_catch_events(&dioxus_doc, hit.node_id))
        .unwrap_or(false);
    if should_catch_events {
        keyboard_input_events.clear();
        keys.reset_all();
    }

    dioxus_doc.resolve();
}

fn bevy_key_to_blitz_key(key: &BevyKey) -> Key {
    match key {
        BevyKey::Character(c) => Key::Character(c.to_string()),
        BevyKey::Unidentified(_) => Key::Unidentified,
        BevyKey::Dead(_) => Key::Dead,
        BevyKey::Alt => Key::Alt,
        BevyKey::AltGraph => Key::AltGraph,
        BevyKey::CapsLock => Key::CapsLock,
        BevyKey::Control => Key::Control,
        BevyKey::Fn => Key::Fn,
        BevyKey::FnLock => Key::FnLock,
        BevyKey::NumLock => Key::Meta,
        BevyKey::ScrollLock => Key::NumLock,
        BevyKey::Shift => Key::ScrollLock,
        BevyKey::Symbol => Key::Shift,
        BevyKey::SymbolLock => Key::Symbol,
        BevyKey::Meta => Key::SymbolLock,
        BevyKey::Hyper => Key::Hyper,
        BevyKey::Super => Key::Super,
        BevyKey::Enter => Key::Enter,
        BevyKey::Tab => Key::Tab,
        BevyKey::Space => Key::Character(" ".to_string()),
        BevyKey::ArrowDown => Key::ArrowDown,
        BevyKey::ArrowLeft => Key::ArrowLeft,
        BevyKey::ArrowRight => Key::ArrowRight,
        BevyKey::ArrowUp => Key::ArrowUp,
        BevyKey::End => Key::End,
        BevyKey::Home => Key::Home,
        BevyKey::PageDown => Key::PageDown,
        BevyKey::PageUp => Key::PageUp,
        BevyKey::Backspace => Key::Backspace,
        BevyKey::Clear => Key::Clear,
        BevyKey::Copy => Key::Copy,
        BevyKey::CrSel => Key::CrSel,
        BevyKey::Cut => Key::Cut,
        BevyKey::Delete => Key::Delete,
        BevyKey::EraseEof => Key::EraseEof,
        BevyKey::ExSel => Key::ExSel,
        BevyKey::Insert => Key::Insert,
        BevyKey::Paste => Key::Paste,
        BevyKey::Redo => Key::Redo,
        BevyKey::Undo => Key::Undo,
        BevyKey::Accept => Key::Accept,
        BevyKey::Again => Key::Again,
        BevyKey::Attn => Key::Attn,
        BevyKey::Cancel => Key::Cancel,
        BevyKey::ContextMenu => Key::ContextMenu,
        BevyKey::Escape => Key::Escape,
        BevyKey::Execute => Key::Execute,
        BevyKey::Find => Key::Find,
        BevyKey::Help => Key::Help,
        BevyKey::Pause => Key::Pause,
        BevyKey::Play => Key::Play,
        BevyKey::Props => Key::Props,
        BevyKey::Select => Key::Select,
        BevyKey::ZoomIn => Key::ZoomIn,
        BevyKey::ZoomOut => Key::ZoomOut,
        BevyKey::BrightnessDown => Key::BrightnessDown,
        BevyKey::BrightnessUp => Key::BrightnessUp,
        BevyKey::Eject => Key::Eject,
        BevyKey::LogOff => Key::LogOff,
        BevyKey::Power => Key::Power,
        BevyKey::PowerOff => Key::PowerOff,
        BevyKey::PrintScreen => Key::PrintScreen,
        BevyKey::Hibernate => Key::Hibernate,
        BevyKey::Standby => Key::Standby,
        BevyKey::WakeUp => Key::WakeUp,
        BevyKey::AllCandidates => Key::AllCandidates,
        BevyKey::Alphanumeric => Key::Alphanumeric,
        BevyKey::CodeInput => Key::CodeInput,
        BevyKey::Compose => Key::Compose,
        BevyKey::Convert => Key::Convert,
        BevyKey::FinalMode => Key::FinalMode,
        BevyKey::GroupFirst => Key::GroupFirst,
        BevyKey::GroupLast => Key::GroupLast,
        BevyKey::GroupNext => Key::GroupNext,
        BevyKey::GroupPrevious => Key::GroupPrevious,
        BevyKey::ModeChange => Key::ModeChange,
        BevyKey::NextCandidate => Key::NextCandidate,
        BevyKey::NonConvert => Key::NonConvert,
        BevyKey::PreviousCandidate => Key::PreviousCandidate,
        BevyKey::Process => Key::Process,
        BevyKey::SingleCandidate => Key::SingleCandidate,
        BevyKey::HangulMode => Key::HangulMode,
        BevyKey::HanjaMode => Key::HanjaMode,
        BevyKey::JunjaMode => Key::JunjaMode,
        BevyKey::Eisu => Key::Eisu,
        BevyKey::Hankaku => Key::Hankaku,
        BevyKey::Hiragana => Key::Hiragana,
        BevyKey::HiraganaKatakana => Key::HiraganaKatakana,
        BevyKey::KanaMode => Key::KanaMode,
        BevyKey::KanjiMode => Key::KanjiMode,
        BevyKey::Katakana => Key::Katakana,
        BevyKey::Romaji => Key::Romaji,
        BevyKey::Zenkaku => Key::Zenkaku,
        BevyKey::ZenkakuHankaku => Key::ZenkakuHankaku,
        BevyKey::Soft1 => Key::Soft1,
        BevyKey::Soft2 => Key::Soft2,
        BevyKey::Soft3 => Key::Soft3,
        BevyKey::Soft4 => Key::Soft4,
        BevyKey::ChannelDown => Key::ChannelDown,
        BevyKey::ChannelUp => Key::ChannelUp,
        BevyKey::Close => Key::Close,
        BevyKey::MailForward => Key::MailForward,
        BevyKey::MailReply => Key::MailReply,
        BevyKey::MailSend => Key::MailSend,
        BevyKey::MediaClose => Key::MediaClose,
        BevyKey::MediaFastForward => Key::MediaFastForward,
        BevyKey::MediaPause => Key::MediaPause,
        BevyKey::MediaPlay => Key::MediaPlay,
        BevyKey::MediaPlayPause => Key::MediaPlayPause,
        BevyKey::MediaRecord => Key::MediaRecord,
        BevyKey::MediaRewind => Key::MediaRewind,
        BevyKey::MediaStop => Key::MediaStop,
        BevyKey::MediaTrackNext => Key::MediaTrackNext,
        BevyKey::MediaTrackPrevious => Key::MediaTrackPrevious,
        BevyKey::New => Key::New,
        BevyKey::Open => Key::Open,
        BevyKey::Print => Key::Print,
        BevyKey::Save => Key::Save,
        BevyKey::SpellCheck => Key::SpellCheck,
        BevyKey::Key11 => Key::Key11,
        BevyKey::Key12 => Key::Key12,
        BevyKey::AudioBalanceLeft => Key::AudioBalanceLeft,
        BevyKey::AudioBalanceRight => Key::AudioBalanceRight,
        BevyKey::AudioBassBoostDown => Key::AudioBassBoostDown,
        BevyKey::AudioBassBoostToggle => Key::AudioBassBoostToggle,
        BevyKey::AudioBassBoostUp => Key::AudioBassBoostUp,
        BevyKey::AudioFaderFront => Key::AudioFaderFront,
        BevyKey::AudioFaderRear => Key::AudioFaderRear,
        BevyKey::AudioSurroundModeNext => Key::AudioSurroundModeNext,
        BevyKey::AudioTrebleDown => Key::AudioTrebleDown,
        BevyKey::AudioTrebleUp => Key::AudioTrebleUp,
        BevyKey::AudioVolumeDown => Key::AudioVolumeDown,
        BevyKey::AudioVolumeUp => Key::AudioVolumeUp,
        BevyKey::AudioVolumeMute => Key::AudioVolumeMute,
        BevyKey::MicrophoneToggle => Key::MicrophoneToggle,
        BevyKey::MicrophoneVolumeDown => Key::MicrophoneVolumeDown,
        BevyKey::MicrophoneVolumeUp => Key::MicrophoneVolumeUp,
        BevyKey::MicrophoneVolumeMute => Key::MicrophoneVolumeMute,
        BevyKey::SpeechCorrectionList => Key::SpeechCorrectionList,
        BevyKey::SpeechInputToggle => Key::SpeechInputToggle,
        BevyKey::LaunchApplication1 => Key::LaunchApplication1,
        BevyKey::LaunchApplication2 => Key::LaunchApplication2,
        BevyKey::LaunchCalendar => Key::LaunchCalendar,
        BevyKey::LaunchContacts => Key::LaunchContacts,
        BevyKey::LaunchMail => Key::LaunchMail,
        BevyKey::LaunchMediaPlayer => Key::LaunchMediaPlayer,
        BevyKey::LaunchMusicPlayer => Key::LaunchMusicPlayer,
        BevyKey::LaunchPhone => Key::LaunchPhone,
        BevyKey::LaunchScreenSaver => Key::LaunchScreenSaver,
        BevyKey::LaunchSpreadsheet => Key::LaunchSpreadsheet,
        BevyKey::LaunchWebBrowser => Key::LaunchWebBrowser,
        BevyKey::LaunchWebCam => Key::LaunchWebCam,
        BevyKey::LaunchWordProcessor => Key::LaunchWordProcessor,
        BevyKey::BrowserBack => Key::BrowserBack,
        BevyKey::BrowserFavorites => Key::BrowserFavorites,
        BevyKey::BrowserForward => Key::BrowserForward,
        BevyKey::BrowserHome => Key::BrowserHome,
        BevyKey::BrowserRefresh => Key::BrowserRefresh,
        BevyKey::BrowserSearch => Key::BrowserSearch,
        BevyKey::BrowserStop => Key::BrowserStop,
        BevyKey::AppSwitch => Key::AppSwitch,
        BevyKey::Call => Key::Call,
        BevyKey::Camera => Key::Camera,
        BevyKey::CameraFocus => Key::CameraFocus,
        BevyKey::EndCall => Key::EndCall,
        BevyKey::GoBack => Key::GoBack,
        BevyKey::GoHome => Key::GoHome,
        BevyKey::HeadsetHook => Key::HeadsetHook,
        BevyKey::LastNumberRedial => Key::LastNumberRedial,
        BevyKey::Notification => Key::Notification,
        BevyKey::MannerMode => Key::MannerMode,
        BevyKey::VoiceDial => Key::VoiceDial,
        BevyKey::TV => Key::TV,
        BevyKey::TV3DMode => Key::TV3DMode,
        BevyKey::TVAntennaCable => Key::TVAntennaCable,
        BevyKey::TVAudioDescription => Key::TVAudioDescription,
        BevyKey::TVAudioDescriptionMixDown => Key::TVAudioDescriptionMixDown,
        BevyKey::TVAudioDescriptionMixUp => Key::TVAudioDescriptionMixUp,
        BevyKey::TVContentsMenu => Key::TVContentsMenu,
        BevyKey::TVDataService => Key::TVDataService,
        BevyKey::TVInput => Key::TVInput,
        BevyKey::TVInputComponent1 => Key::TVInputComponent1,
        BevyKey::TVInputComponent2 => Key::TVInputComponent2,
        BevyKey::TVInputComposite1 => Key::TVInputComposite1,
        BevyKey::TVInputComposite2 => Key::TVInputComposite2,
        BevyKey::TVInputHDMI1 => Key::TVInputHDMI1,
        BevyKey::TVInputHDMI2 => Key::TVInputHDMI2,
        BevyKey::TVInputHDMI3 => Key::TVInputHDMI3,
        BevyKey::TVInputHDMI4 => Key::TVInputHDMI4,
        BevyKey::TVInputVGA1 => Key::TVInputVGA1,
        BevyKey::TVMediaContext => Key::TVMediaContext,
        BevyKey::TVNetwork => Key::TVNetwork,
        BevyKey::TVNumberEntry => Key::TVNumberEntry,
        BevyKey::TVPower => Key::TVPower,
        BevyKey::TVRadioService => Key::TVRadioService,
        BevyKey::TVSatellite => Key::TVSatellite,
        BevyKey::TVSatelliteBS => Key::TVSatelliteBS,
        BevyKey::TVSatelliteCS => Key::TVSatelliteCS,
        BevyKey::TVSatelliteToggle => Key::TVSatelliteToggle,
        BevyKey::TVTerrestrialAnalog => Key::TVTerrestrialAnalog,
        BevyKey::TVTerrestrialDigital => Key::TVTerrestrialDigital,
        BevyKey::TVTimer => Key::TVTimer,
        BevyKey::AVRInput => Key::AVRInput,
        BevyKey::AVRPower => Key::AVRPower,
        BevyKey::ColorF0Red => Key::ColorF0Red,
        BevyKey::ColorF1Green => Key::ColorF1Green,
        BevyKey::ColorF2Yellow => Key::ColorF2Yellow,
        BevyKey::ColorF3Blue => Key::ColorF3Blue,
        BevyKey::ColorF4Grey => Key::ColorF4Grey,
        BevyKey::ColorF5Brown => Key::ColorF5Brown,
        BevyKey::ClosedCaptionToggle => Key::ClosedCaptionToggle,
        BevyKey::Dimmer => Key::Dimmer,
        BevyKey::DisplaySwap => Key::DisplaySwap,
        BevyKey::DVR => Key::DVR,
        BevyKey::Exit => Key::Exit,
        BevyKey::FavoriteClear0 => Key::FavoriteClear0,
        BevyKey::FavoriteClear1 => Key::FavoriteClear1,
        BevyKey::FavoriteClear2 => Key::FavoriteClear2,
        BevyKey::FavoriteClear3 => Key::FavoriteClear3,
        BevyKey::FavoriteRecall0 => Key::FavoriteRecall0,
        BevyKey::FavoriteRecall1 => Key::FavoriteRecall1,
        BevyKey::FavoriteRecall2 => Key::FavoriteRecall2,
        BevyKey::FavoriteRecall3 => Key::FavoriteRecall3,
        BevyKey::FavoriteStore0 => Key::FavoriteStore0,
        BevyKey::FavoriteStore1 => Key::FavoriteStore1,
        BevyKey::FavoriteStore2 => Key::FavoriteStore2,
        BevyKey::FavoriteStore3 => Key::FavoriteStore3,
        BevyKey::Guide => Key::Guide,
        BevyKey::GuideNextDay => Key::GuideNextDay,
        BevyKey::GuidePreviousDay => Key::GuidePreviousDay,
        BevyKey::Info => Key::Info,
        BevyKey::InstantReplay => Key::InstantReplay,
        BevyKey::Link => Key::Link,
        BevyKey::ListProgram => Key::ListProgram,
        BevyKey::LiveContent => Key::LiveContent,
        BevyKey::Lock => Key::Lock,
        BevyKey::MediaApps => Key::MediaApps,
        BevyKey::MediaAudioTrack => Key::MediaAudioTrack,
        BevyKey::MediaLast => Key::MediaLast,
        BevyKey::MediaSkipBackward => Key::MediaSkipBackward,
        BevyKey::MediaSkipForward => Key::MediaSkipForward,
        BevyKey::MediaStepBackward => Key::MediaStepBackward,
        BevyKey::MediaStepForward => Key::MediaStepForward,
        BevyKey::MediaTopMenu => Key::MediaTopMenu,
        BevyKey::NavigateIn => Key::NavigateIn,
        BevyKey::NavigateNext => Key::NavigateNext,
        BevyKey::NavigateOut => Key::NavigateOut,
        BevyKey::NavigatePrevious => Key::NavigatePrevious,
        BevyKey::NextFavoriteChannel => Key::NextFavoriteChannel,
        BevyKey::NextUserProfile => Key::NextUserProfile,
        BevyKey::OnDemand => Key::OnDemand,
        BevyKey::Pairing => Key::Pairing,
        BevyKey::PinPDown => Key::PinPDown,
        BevyKey::PinPMove => Key::PinPMove,
        BevyKey::PinPToggle => Key::PinPToggle,
        BevyKey::PinPUp => Key::PinPUp,
        BevyKey::PlaySpeedDown => Key::PlaySpeedDown,
        BevyKey::PlaySpeedReset => Key::PlaySpeedReset,
        BevyKey::PlaySpeedUp => Key::PlaySpeedUp,
        BevyKey::RandomToggle => Key::RandomToggle,
        BevyKey::RcLowBattery => Key::RcLowBattery,
        BevyKey::RecordSpeedNext => Key::RecordSpeedNext,
        BevyKey::RfBypass => Key::RfBypass,
        BevyKey::ScanChannelsToggle => Key::ScanChannelsToggle,
        BevyKey::ScreenModeNext => Key::ScreenModeNext,
        BevyKey::Settings => Key::Settings,
        BevyKey::SplitScreenToggle => Key::SplitScreenToggle,
        BevyKey::STBInput => Key::STBInput,
        BevyKey::STBPower => Key::STBPower,
        BevyKey::Subtitle => Key::Subtitle,
        BevyKey::Teletext => Key::Teletext,
        BevyKey::VideoModeNext => Key::VideoModeNext,
        BevyKey::Wink => Key::Wink,
        BevyKey::ZoomToggle => Key::ZoomToggle,
        BevyKey::F1 => Key::F1,
        BevyKey::F2 => Key::F2,
        BevyKey::F3 => Key::F3,
        BevyKey::F4 => Key::F4,
        BevyKey::F5 => Key::F5,
        BevyKey::F6 => Key::F6,
        BevyKey::F7 => Key::F7,
        BevyKey::F8 => Key::F8,
        BevyKey::F9 => Key::F9,
        BevyKey::F10 => Key::F10,
        BevyKey::F11 => Key::F11,
        BevyKey::F12 => Key::F12,
        BevyKey::F13 => Key::F13,
        BevyKey::F14 => Key::F14,
        BevyKey::F15 => Key::F15,
        BevyKey::F16 => Key::F16,
        BevyKey::F17 => Key::F17,
        BevyKey::F18 => Key::F18,
        BevyKey::F19 => Key::F19,
        BevyKey::F20 => Key::F20,
        BevyKey::F21 => Key::F21,
        BevyKey::F22 => Key::F22,
        BevyKey::F23 => Key::F23,
        BevyKey::F24 => Key::F24,
        BevyKey::F25 => Key::F25,
        BevyKey::F26 => Key::F26,
        BevyKey::F27 => Key::F27,
        BevyKey::F28 => Key::F28,
        BevyKey::F29 => Key::F29,
        BevyKey::F30 => Key::F30,
        BevyKey::F31 => Key::F31,
        BevyKey::F32 => Key::F32,
        BevyKey::F33 => Key::F33,
        BevyKey::F34 => Key::F34,
        BevyKey::F35 => Key::F35,
        _ => Key::Unidentified,
    }
}

fn bevy_key_code_to_blitz_code(key_code: &BevyKeyCode) -> Code {
    match key_code {
        BevyKeyCode::Unidentified(_) => Code::Unidentified,
        BevyKeyCode::Backquote => Code::Backquote,
        BevyKeyCode::Backslash => Code::Backslash,
        BevyKeyCode::BracketLeft => Code::BracketLeft,
        BevyKeyCode::BracketRight => Code::BracketRight,
        BevyKeyCode::Comma => Code::Comma,
        BevyKeyCode::Digit0 => Code::Digit0,
        BevyKeyCode::Digit1 => Code::Digit1,
        BevyKeyCode::Digit2 => Code::Digit2,
        BevyKeyCode::Digit3 => Code::Digit3,
        BevyKeyCode::Digit4 => Code::Digit4,
        BevyKeyCode::Digit5 => Code::Digit5,
        BevyKeyCode::Digit6 => Code::Digit6,
        BevyKeyCode::Digit7 => Code::Digit7,
        BevyKeyCode::Digit8 => Code::Digit8,
        BevyKeyCode::Digit9 => Code::Digit9,
        BevyKeyCode::Equal => Code::Equal,
        BevyKeyCode::IntlBackslash => Code::IntlBackslash,
        BevyKeyCode::IntlRo => Code::IntlRo,
        BevyKeyCode::IntlYen => Code::IntlYen,
        BevyKeyCode::KeyA => Code::KeyA,
        BevyKeyCode::KeyB => Code::KeyB,
        BevyKeyCode::KeyC => Code::KeyC,
        BevyKeyCode::KeyD => Code::KeyD,
        BevyKeyCode::KeyE => Code::KeyE,
        BevyKeyCode::KeyF => Code::KeyF,
        BevyKeyCode::KeyG => Code::KeyG,
        BevyKeyCode::KeyH => Code::KeyH,
        BevyKeyCode::KeyI => Code::KeyI,
        BevyKeyCode::KeyJ => Code::KeyJ,
        BevyKeyCode::KeyK => Code::KeyK,
        BevyKeyCode::KeyL => Code::KeyL,
        BevyKeyCode::KeyM => Code::KeyM,
        BevyKeyCode::KeyN => Code::KeyN,
        BevyKeyCode::KeyO => Code::KeyO,
        BevyKeyCode::KeyP => Code::KeyP,
        BevyKeyCode::KeyQ => Code::KeyQ,
        BevyKeyCode::KeyR => Code::KeyR,
        BevyKeyCode::KeyS => Code::KeyS,
        BevyKeyCode::KeyT => Code::KeyT,
        BevyKeyCode::KeyU => Code::KeyU,
        BevyKeyCode::KeyV => Code::KeyV,
        BevyKeyCode::KeyW => Code::KeyW,
        BevyKeyCode::KeyX => Code::KeyX,
        BevyKeyCode::KeyY => Code::KeyY,
        BevyKeyCode::KeyZ => Code::KeyZ,
        BevyKeyCode::Minus => Code::Minus,
        BevyKeyCode::Period => Code::Period,
        BevyKeyCode::Quote => Code::Quote,
        BevyKeyCode::Semicolon => Code::Semicolon,
        BevyKeyCode::Slash => Code::Slash,
        BevyKeyCode::AltLeft => Code::AltLeft,
        BevyKeyCode::AltRight => Code::AltRight,
        BevyKeyCode::Backspace => Code::Backspace,
        BevyKeyCode::CapsLock => Code::CapsLock,
        BevyKeyCode::ContextMenu => Code::ContextMenu,
        BevyKeyCode::ControlLeft => Code::ControlLeft,
        BevyKeyCode::ControlRight => Code::ControlRight,
        BevyKeyCode::Enter => Code::Enter,
        BevyKeyCode::SuperLeft => Code::MetaLeft,
        BevyKeyCode::SuperRight => Code::MetaRight,
        BevyKeyCode::ShiftLeft => Code::ShiftLeft,
        BevyKeyCode::ShiftRight => Code::ShiftRight,
        BevyKeyCode::Space => Code::Space,
        BevyKeyCode::Tab => Code::Tab,
        BevyKeyCode::Convert => Code::Convert,
        BevyKeyCode::KanaMode => Code::KanaMode,
        BevyKeyCode::Lang1 => Code::Lang1,
        BevyKeyCode::Lang2 => Code::Lang2,
        BevyKeyCode::Lang3 => Code::Lang3,
        BevyKeyCode::Lang4 => Code::Lang4,
        BevyKeyCode::Lang5 => Code::Lang5,
        BevyKeyCode::NonConvert => Code::NonConvert,
        BevyKeyCode::Delete => Code::Delete,
        BevyKeyCode::End => Code::End,
        BevyKeyCode::Help => Code::Help,
        BevyKeyCode::Home => Code::Home,
        BevyKeyCode::Insert => Code::Insert,
        BevyKeyCode::PageDown => Code::PageDown,
        BevyKeyCode::PageUp => Code::PageUp,
        BevyKeyCode::ArrowDown => Code::ArrowDown,
        BevyKeyCode::ArrowLeft => Code::ArrowLeft,
        BevyKeyCode::ArrowRight => Code::ArrowRight,
        BevyKeyCode::ArrowUp => Code::ArrowUp,
        BevyKeyCode::NumLock => Code::NumLock,
        BevyKeyCode::Numpad0 => Code::Numpad0,
        BevyKeyCode::Numpad1 => Code::Numpad1,
        BevyKeyCode::Numpad2 => Code::Numpad2,
        BevyKeyCode::Numpad3 => Code::Numpad3,
        BevyKeyCode::Numpad4 => Code::Numpad4,
        BevyKeyCode::Numpad5 => Code::Numpad5,
        BevyKeyCode::Numpad6 => Code::Numpad6,
        BevyKeyCode::Numpad7 => Code::Numpad7,
        BevyKeyCode::Numpad8 => Code::Numpad8,
        BevyKeyCode::Numpad9 => Code::Numpad9,
        BevyKeyCode::NumpadAdd => Code::NumpadAdd,
        BevyKeyCode::NumpadBackspace => Code::NumpadBackspace,
        BevyKeyCode::NumpadClear => Code::NumpadClear,
        BevyKeyCode::NumpadClearEntry => Code::NumpadClearEntry,
        BevyKeyCode::NumpadComma => Code::NumpadComma,
        BevyKeyCode::NumpadDecimal => Code::NumpadDecimal,
        BevyKeyCode::NumpadDivide => Code::NumpadDivide,
        BevyKeyCode::NumpadEnter => Code::NumpadEnter,
        BevyKeyCode::NumpadEqual => Code::NumpadEqual,
        BevyKeyCode::NumpadHash => Code::NumpadHash,
        BevyKeyCode::NumpadMemoryAdd => Code::NumpadMemoryAdd,
        BevyKeyCode::NumpadMemoryClear => Code::NumpadMemoryClear,
        BevyKeyCode::NumpadMemoryRecall => Code::NumpadMemoryRecall,
        BevyKeyCode::NumpadMemoryStore => Code::NumpadMemoryStore,
        BevyKeyCode::NumpadMemorySubtract => Code::NumpadMemorySubtract,
        BevyKeyCode::NumpadMultiply => Code::NumpadMultiply,
        BevyKeyCode::NumpadParenLeft => Code::NumpadParenLeft,
        BevyKeyCode::NumpadParenRight => Code::NumpadParenRight,
        BevyKeyCode::NumpadStar => Code::NumpadStar,
        BevyKeyCode::NumpadSubtract => Code::NumpadSubtract,
        BevyKeyCode::Escape => Code::Escape,
        BevyKeyCode::Fn => Code::Fn,
        BevyKeyCode::FnLock => Code::FnLock,
        BevyKeyCode::PrintScreen => Code::PrintScreen,
        BevyKeyCode::ScrollLock => Code::ScrollLock,
        BevyKeyCode::Pause => Code::Pause,
        BevyKeyCode::BrowserBack => Code::BrowserBack,
        BevyKeyCode::BrowserFavorites => Code::BrowserFavorites,
        BevyKeyCode::BrowserForward => Code::BrowserForward,
        BevyKeyCode::BrowserHome => Code::BrowserHome,
        BevyKeyCode::BrowserRefresh => Code::BrowserRefresh,
        BevyKeyCode::BrowserSearch => Code::BrowserSearch,
        BevyKeyCode::BrowserStop => Code::BrowserStop,
        BevyKeyCode::Eject => Code::Eject,
        BevyKeyCode::LaunchApp1 => Code::LaunchApp1,
        BevyKeyCode::LaunchApp2 => Code::LaunchApp2,
        BevyKeyCode::LaunchMail => Code::LaunchMail,
        BevyKeyCode::MediaPlayPause => Code::MediaPlayPause,
        BevyKeyCode::MediaSelect => Code::MediaSelect,
        BevyKeyCode::MediaStop => Code::MediaStop,
        BevyKeyCode::MediaTrackNext => Code::MediaTrackNext,
        BevyKeyCode::MediaTrackPrevious => Code::MediaTrackPrevious,
        BevyKeyCode::Power => Code::Power,
        BevyKeyCode::Sleep => Code::Sleep,
        BevyKeyCode::AudioVolumeDown => Code::AudioVolumeDown,
        BevyKeyCode::AudioVolumeMute => Code::AudioVolumeMute,
        BevyKeyCode::AudioVolumeUp => Code::AudioVolumeUp,
        BevyKeyCode::WakeUp => Code::WakeUp,
        BevyKeyCode::Meta => Code::Hyper,
        BevyKeyCode::Hyper => Code::Super,
        BevyKeyCode::Turbo => Code::Turbo,
        BevyKeyCode::Abort => Code::Abort,
        BevyKeyCode::Resume => Code::Resume,
        BevyKeyCode::Suspend => Code::Suspend,
        BevyKeyCode::Again => Code::Again,
        BevyKeyCode::Copy => Code::Copy,
        BevyKeyCode::Cut => Code::Cut,
        BevyKeyCode::Find => Code::Find,
        BevyKeyCode::Open => Code::Open,
        BevyKeyCode::Paste => Code::Paste,
        BevyKeyCode::Props => Code::Props,
        BevyKeyCode::Select => Code::Select,
        BevyKeyCode::Undo => Code::Undo,
        BevyKeyCode::Hiragana => Code::Hiragana,
        BevyKeyCode::Katakana => Code::Katakana,
        BevyKeyCode::F1 => Code::F1,
        BevyKeyCode::F2 => Code::F2,
        BevyKeyCode::F3 => Code::F3,
        BevyKeyCode::F4 => Code::F4,
        BevyKeyCode::F5 => Code::F5,
        BevyKeyCode::F6 => Code::F6,
        BevyKeyCode::F7 => Code::F7,
        BevyKeyCode::F8 => Code::F8,
        BevyKeyCode::F9 => Code::F9,
        BevyKeyCode::F10 => Code::F10,
        BevyKeyCode::F11 => Code::F11,
        BevyKeyCode::F12 => Code::F12,
        BevyKeyCode::F13 => Code::F13,
        BevyKeyCode::F14 => Code::F14,
        BevyKeyCode::F15 => Code::F15,
        BevyKeyCode::F16 => Code::F16,
        BevyKeyCode::F17 => Code::F17,
        BevyKeyCode::F18 => Code::F18,
        BevyKeyCode::F19 => Code::F19,
        BevyKeyCode::F20 => Code::F20,
        BevyKeyCode::F21 => Code::F21,
        BevyKeyCode::F22 => Code::F22,
        BevyKeyCode::F23 => Code::F23,
        BevyKeyCode::F24 => Code::F24,
        BevyKeyCode::F25 => Code::F25,
        BevyKeyCode::F26 => Code::F26,
        BevyKeyCode::F27 => Code::F27,
        BevyKeyCode::F28 => Code::F28,
        BevyKeyCode::F29 => Code::F29,
        BevyKeyCode::F30 => Code::F30,
        BevyKeyCode::F31 => Code::F31,
        BevyKeyCode::F32 => Code::F32,
        BevyKeyCode::F33 => Code::F33,
        BevyKeyCode::F34 => Code::F34,
        BevyKeyCode::F35 => Code::F35,
    }
}
